---

- hosts: localhost
  sudo: yes
  roles:
    - role: provision

      provision_repositories:
        - "https://repos.fedorapeople.org/repos/spot/chromium/fedora-chromium-stable.repo"
        - "http://negativo17.org/repos/fedora-spotify.repo"
        - "http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo"

      provision_enable_rpmfusion: yes

      provision_packages:
        - adwaita-gtk2-theme
        - openssh-server
        - zsh

        # office
        - dropbox
        - thunderbird
        - libreoffice
        - cups

        # virtualization
        - vagrant
        - libvirt
        - libvirt-devel
        - virt-manager
        - vagrant-libvirt
        - vagrant-libvirt-doc
        - vagrant-lxc
        - vagrant-lxc-doc

        # xmonad
        - xmonad
        - xmonad-mate
        - ghc-xmonad-devel
        - ghc-xmonad-contrib
        - ghc-xmonad-contrib-devel

      provision_services:
        - name: libvirtd
        - name: cups
        - name: sshd
        - name: firewalld

      provision_users:
        - name: badi
          shell: /bin/zsh
          groups:
            - badi
            - wheel
            - libvirt

      provision_kernel_modules:
        - name: kvm-intel
          parameters:
            - nested=y
          state: reloaded

      provision_secure_sshd: yes

      provision_yubikey: yes

  tasks:
    - name: setup gtkrc
      sudo: no
      file:
        src: /usr/share/themes/Adwaita/gtk-2.0/gtkrc
        path: "/home/{{ item }}/.gtkrc-2.0"
        state: link
        owner: badi
        group: badi
      with_items:
        - badi
